# loki-config.yaml - Versión FINALMENTE CORREGIDA para Loki 2.9.0 con boltdb-shipper
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /tmp/loki/wal
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
    heartbeat_timeout: 1m

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index: # <-- ¡Importante! 'period' va dentro de 'index'
        period: 24h # <-- Aquí está la ubicación correcta

compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem

chunk_store_config:
  max_look_back_period: 0s

limits_config:
  retention_period: 720h # Ejemplo: 30 días de retención

memberlist:
  join_members:
    - loki