# prometheus.yml
global:
  scrape_interval: 15s # Raspa métricas cada 15 segundos
  evaluation_interval: 15s # Evalúa reglas cada 15 segundos

scrape_configs:
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus' # Endpoint de métricas de Spring Boot Actuator
    static_configs:
      - targets:
          - 'api-gateway:9090'
          - 'eureka-server:8761'
          - 'inventory-service:8080'
          - 'order-service:8081'
          - 'payment-service:8082'
          - 'product-service:8083'